// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzxcyqadsxhfgdtmeocx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eGN5cWFkc3hoZmdkdG1lb2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzU0NzQsImV4cCI6MjA1NzI1MTQ3NH0.pS4Dqq1moUaGDL8khYsSvXt6sAb6qKxPlLK6_NshU-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);